language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

branches:
  only:
    - master

before_script:
  - composer install --no-interaction --prefer-source

script: composer test